# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-31 00:42
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitrequest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='audioparts/%Y-%m-%d')),
                ('predictions', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), size=None)),
                ('hasBeenValidated', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='audioSnippets',
            field=models.ManyToManyField(related_name='docForSnippet', to='hitrequest.AudioSnippet'),
        ),
    ]
