# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-02 02:04
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitrequest', '0002_auto_20161030_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiosnippet',
            name='activeHITId',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='audiosnippet',
            name='incorrectWords',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(), default=[], size=None), default=[], size=None),
        ),
    ]
