# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-02 02:05
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitrequest', '0003_auto_20161101_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiosnippet',
            name='predictions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), default=[], size=None),
        ),
    ]
