# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-02 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitrequest', '0004_auto_20161101_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiosnippet',
            name='activeHITId',
            field=models.CharField(max_length=30),
        ),
    ]
