# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-02 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitrequest', '0005_auto_20161101_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiosnippet',
            name='isComplete',
            field=models.BooleanField(default=False),
        ),
    ]
