# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-02 21:24
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hitrequest', '0006_audiosnippet_iscomplete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiosnippet',
            name='incorrectWords'
        ),
        migrations.AddField(
            model_name='audiosnippet',
            name='incorrectWords',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django.contrib.postgres.fields.jsonb.JSONField(
                    default={}),
                default=[],
            size=None),
        ),
    ]
