# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-02 21:57
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hitrequest', '0007_auto_20161102_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiosnippet',
            name='incorrectWords'
        ),
        migrations.AddField(
            model_name='audiosnippet',
            name='incorrectWords',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'bools': []}),
        ),
    ]
